// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjmiDc9kIOICA5PM1be3rzRzhp-QCWLYI',
    appId: '1:662929528256:ios:0becb1bdb0e86e76e92425',
    messagingSenderId: '662929528256',
    projectId: 'madhyamik-app-2c80d',
    databaseURL: 'https://madhyamik-app-2c80d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madhyamik-app-2c80d.firebasestorage.app',
    iosBundleId: 'com.example.myMadhyamikApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjmiDc9kIOICA5PM1be3rzRzhp-QCWLYI',
    appId: '1:662929528256:ios:0becb1bdb0e86e76e92425',
    messagingSenderId: '662929528256',
    projectId: 'madhyamik-app-2c80d',
    databaseURL: 'https://madhyamik-app-2c80d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madhyamik-app-2c80d.firebasestorage.app',
    iosBundleId: 'com.example.myMadhyamikApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5fkBKoGrStVDa-DsYppZ8GOnk_OL_syU',
    appId: '1:662929528256:web:41a0b556e440ecf1e92425',
    messagingSenderId: '662929528256',
    projectId: 'madhyamik-app-2c80d',
    authDomain: 'madhyamik-app-2c80d.firebaseapp.com',
    databaseURL: 'https://madhyamik-app-2c80d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madhyamik-app-2c80d.firebasestorage.app',
    measurementId: 'G-4MCJ3CXPEH',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5fkBKoGrStVDa-DsYppZ8GOnk_OL_syU',
    appId: '1:662929528256:web:0ad17e7ce040d1e7e92425',
    messagingSenderId: '662929528256',
    projectId: 'madhyamik-app-2c80d',
    authDomain: 'madhyamik-app-2c80d.firebaseapp.com',
    databaseURL: 'https://madhyamik-app-2c80d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madhyamik-app-2c80d.firebasestorage.app',
    measurementId: 'G-Y6K5Z77HF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZMNp8TEv7kurG7MTAdE3UuzhGOjLHwxY',
    appId: '1:662929528256:android:2c0d5ac9fa17e904e92425',
    messagingSenderId: '662929528256',
    projectId: 'madhyamik-app-2c80d',
    databaseURL: 'https://madhyamik-app-2c80d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'madhyamik-app-2c80d.firebasestorage.app',
  );

}